In [85]:
import pandas as pd
import numpy as np

In [239]:
file = pd.read_csv('PriorityCBG.csv', header=[0])

In [240]:
df = pd.DataFrame(file)

In [241]:
df.head()

,Unnamed: 0,X,census_bg,Total.Area.in.acres,Total.Land.Area.in.acres,Tree.Canopy.in.acres,Tree.Canopy.area.in.percent,Vegetation.in.acres,Vegetation.Percentage,Building.area.in.acres,...,Total.White.Population,Total.African.American.Population,Total.American.Indian.Population,Total.Asian.Population,Total.Native.Hawaiian.Population,Total.Population.of.Other.Races,PovertyPerCapita,UTC_quart,income_quart,UTCacres_quart
0,1,0,110010001004,287.26,166.02,92.93,55.975184,5.89,3.547765,31.54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q4,Q4,Q4
1,2,1,110010002011,133.35,133.34,39.42,29.563522,19.01,14.256787,29.47,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Q3,Q2,Q4
2,3,2,110010002021,47.44,47.44,15.31,32.272344,3.78,7.967960,12.79,...,935.0,43.0,5.0,98.0,0.0,13.0,0.0,Q3,Q4,Q3
3,4,3,110010002022,33.48,33.48,11.52,34.408602,2.86,8.542413,8.84,...,646.0,13.0,1.0,47.0,0.0,12.0,0.0,Q3,Q4,Q2
4,5,4,110010002023,38.17,38.17,9.17,24.024103,1.68,4.401362,13.59,...,757.0,24.0,3.0,50.0,0.0,14.0,0.0,Q2,Q4,Q2

In [242]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 56 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Unnamed: 0                                                          450 non-null    int64
 1   X                                                                   450 non-null    int64
 2   census_bg                                                           450 non-null    int64
 3   Total.Area.in.acres                                                 450 non-null    float64
 4   Total.Land.Area.in.acres                                            450 non-null    float64
 5   Tree.Canopy.in.acres                                                450 non-null    float64
 6   Tree.Canopy.area.in.percent                                         450 non-null    float64
 7   Vegetation.in.acres                                                 450 non-null    float64
 8   Vegetation.Percentage                                               450 non-null    float64
 9   Building.area.in.acres                                              450 non-null    float64
 10  Building.area.in.percent                                            450 non-null    float64
 11  Total.Impervious.Area.in.acres                                      450 non-null    float64
 12  Total.Impervious.Area.in.percent                                    450 non-null    float64
 13  Road.Acres                                                          450 non-null    float64
 14  Road.Area.in.percent                                                450 non-null    float64
 15  Sidewalk.Area.in.acres                                              450 non-null    float64
 16  Sidewalk.Area.in.percent                                            450 non-null    float64
 17  Other.Impervious.Area.in.acres                                      450 non-null    float64
 18  Other.Impervious.Area.in.percent                                    450 non-null    float64
 19  Surface.Water.Area.in.acres                                         450 non-null    float64
 20  Surface.Water.Area.in.percent                                       450 non-null    float64
 21  Soil.area.in.acres                                                  450 non-null    float64
 22  Soil.area.in.percent                                                450 non-null    float64
 23  Urban.Tree.Canopy.area.in.acres                                     450 non-null    float64
 24  Urban.Tree.Canopy.area.percent                                      450 non-null    float64
 25  Possible.Vegetation.Planting.Area.in.acres                          450 non-null    float64
 26  Possible.Vegetation.Planting.Area.in.percent                        450 non-null    float64
 27  Total.Possible.Planting.Area.in.acres                               450 non-null    float64
 28  Total.Possible.Planting.Area.in.percent                             450 non-null    float64
 29  Impervious.Possible.Planting.Area.in.acres                          450 non-null    float64
 30  Impervious.Possible.Planting.Area.in.percent                        450 non-null    float64
 31  Unsuitable.Impervious.Planting.Buildings.and.Roads.Area.in.acres    450 non-null    float64
 32  Unsuitable.Impervious.Planting.Buildings.and.Roads.Area.in.percent  450 non-null    float64
 33  Total.Unsuitable.Planting.Area.in.acres                             450 non-null    float64
 34  Total.Unsuitable.Planting.Area.in.percent                           450 non-null    float64
 35  Unsuitable.Soil.and.Vegetation.Area.in.acres                        450 non-null    float64
 36  Unsuitable.Soil.and.Vegetation.Area.in.percent                      450 non-null    float64
 37  Unsuitable.Other.Land.Area.in.acres                                 450 non-null    float64
 38  Unsuitable.Other.Land.Area.in.percent                               450 non-null    float64
 39  SHAPEAREA                                                           450 non-null    float64
 40  SHAPELEN                                                            450 non-null    float64
 41  Geographic.Area.Name                                                450 non-null    object
 42  Income.in.the.past.12.months.below.poverty.level                    450 non-null    int64
 43  Median.household.income.in.the.past.12.months                       450 non-null    int64
 44  Total.Population                                                    366 non-null    float64
 45  Total.Population.of.one.race                                        366 non-null    float64
 46  Total.White.Population                                              366 non-null    float64
 47  Total.African.American.Population                                   366 non-null    float64
 48  Total.American.Indian.Population                                    366 non-null    float64
 49  Total.Asian.Population                                              366 non-null    float64
 50  Total.Native.Hawaiian.Population                                    366 non-null    float64
 51  Total.Population.of.Other.Races                                     366 non-null    float64
 52  PovertyPerCapita                                                    365 non-null    float64
 53  UTC_quart                                                           450 non-null    object
 54  income_quart                                                        450 non-null    object
 55  UTCacres_quart                                                      450 non-null    object
dtypes: float64(47), int64(5), object(4)
memory usage: 197.0+ KB

In [243]:
df = df.replace({'UTC_quart': 'Q1', 'income_quart': 'Q1'}, .4)
df = df.replace({'UTC_quart': 'Q2', 'income_quart': 'Q2'}, .3)
df = df.replace({'UTC_quart': 'Q3', 'income_quart': 'Q3'}, .2)
df = df.replace({'UTC_quart': 'Q4', 'income_quart': 'Q4'}, .1)

In [244]:
df['Total.Possible.Planting.Area.in.percent2'] = df['Total.Possible.Planting.Area.in.percent']/100
df['Possible.Vegetation.Planting.Area.in.percent2'] = df['Possible.Vegetation.Planting.Area.in.percent']/100

In [245]:
df.head()

,Unnamed: 0,X,census_bg,Total.Area.in.acres,Total.Land.Area.in.acres,Tree.Canopy.in.acres,Tree.Canopy.area.in.percent,Vegetation.in.acres,Vegetation.Percentage,Building.area.in.acres,...,Total.American.Indian.Population,Total.Asian.Population,Total.Native.Hawaiian.Population,Total.Population.of.Other.Races,PovertyPerCapita,UTC_quart,income_quart,UTCacres_quart,Total.Possible.Planting.Area.in.percent2,Possible.Vegetation.Planting.Area.in.percent2
0,1,0,110010001004,287.26,166.02,92.93,55.975184,5.89,3.547765,31.54,...,NaN,NaN,NaN,NaN,NaN,0.1,0.1,Q4,0.123841,0.025479
1,2,1,110010002011,133.35,133.34,39.42,29.563522,19.01,14.256787,29.47,...,0.0,0.0,0.0,0.0,NaN,0.2,0.3,Q4,0.271036,0.114369
2,3,2,110010002021,47.44,47.44,15.31,32.272344,3.78,7.967960,12.79,...,5.0,98.0,0.0,13.0,0.0,0.2,0.1,Q3,0.214587,0.078204
3,4,3,110010002022,33.48,33.48,11.52,34.408602,2.86,8.542413,8.84,...,1.0,47.0,0.0,12.0,0.0,0.2,0.1,Q2,0.227001,0.082139
4,5,4,110010002023,38.17,38.17,9.17,24.024103,1.68,4.401362,13.59,...,3.0,50.0,0.0,14.0,0.0,0.3,0.1,Q2,0.214304,0.043752

In [246]:
df['priority_CBGs'] = (df['UTC_quart'] + df['Total.Possible.Planting.Area.in.percent2'] + df['Possible.Vegetation.Planting.Area.in.percent2'] + df['income_quart'])/2.8

In [247]:
df = df.sort_values(by='priority_CBGs', ascending=False)

In [253]:
df.head()

,census_bg,Total.Area.in.acres,Total.Land.Area.in.acres,Tree.Canopy.in.acres,Tree.Canopy.area.in.percent,Vegetation.in.acres,Vegetation.Percentage,Building.area.in.acres,Building.area.in.percent,Total.Impervious.Area.in.acres,...,Total.Asian.Population,Total.Native.Hawaiian.Population,Total.Population.of.Other.Races,PovertyPerCapita,UTC_quart,income_quart,UTCacres_quart,Total.Possible.Planting.Area.in.percent2,Possible.Vegetation.Planting.Area.in.percent2,priority_CBGs
285,110010076015,171.41,132.72,20.87,15.724834,50.03,37.695901,10.60,7.986739,60.59,...,4.0,0.0,15.0,0.029851,0.4,0.4,Q3,0.454792,0.359479,0.576525
216,110010088042,170.37,170.37,28.55,16.757645,58.66,34.430944,21.67,12.719375,82.94,...,23.0,1.0,76.0,0.035236,0.4,0.4,Q3,0.418618,0.344075,0.558105
300,110010076051,32.16,32.16,6.26,19.465174,9.05,28.140547,6.19,19.247512,16.86,...,4.0,0.0,10.0,0.033467,0.4,0.4,Q1,0.439677,0.281405,0.543244
171,110010033011,61.71,61.71,9.37,15.183925,23.67,38.356830,10.04,16.269648,28.67,...,50.0,0.0,35.0,0.000000,0.4,0.2,Q2,0.536218,0.383568,0.542781
423,110010099031,40.46,40.46,5.08,12.555610,10.48,25.902126,6.53,16.139397,24.81,...,3.0,1.0,14.0,0.028684,0.4,0.3,Q1,0.492832,0.259021,0.518519

In [248]:
df.columns

Index(['Unnamed: 0', 'X', 'census_bg', 'Total.Area.in.acres',
       'Total.Land.Area.in.acres', 'Tree.Canopy.in.acres',
       'Tree.Canopy.area.in.percent', 'Vegetation.in.acres',
       'Vegetation.Percentage', 'Building.area.in.acres',
       'Building.area.in.percent', 'Total.Impervious.Area.in.acres',
       'Total.Impervious.Area.in.percent', 'Road.Acres',
       'Road.Area.in.percent', 'Sidewalk.Area.in.acres',
       'Sidewalk.Area.in.percent', 'Other.Impervious.Area.in.acres',
       'Other.Impervious.Area.in.percent', 'Surface.Water.Area.in.acres',
       'Surface.Water.Area.in.percent', 'Soil.area.in.acres',
       'Soil.area.in.percent', 'Urban.Tree.Canopy.area.in.acres',
       'Urban.Tree.Canopy.area.percent',
       'Possible.Vegetation.Planting.Area.in.acres',
       'Possible.Vegetation.Planting.Area.in.percent',
       'Total.Possible.Planting.Area.in.acres',
       'Total.Possible.Planting.Area.in.percent',
       'Impervious.Possible.Planting.Area.in.acres',
       'Impervious.Possible.Planting.Area.in.percent',
       'Unsuitable.Impervious.Planting.Buildings.and.Roads.Area.in.acres',
       'Unsuitable.Impervious.Planting.Buildings.and.Roads.Area.in.percent',
       'Total.Unsuitable.Planting.Area.in.acres',
       'Total.Unsuitable.Planting.Area.in.percent',
       'Unsuitable.Soil.and.Vegetation.Area.in.acres',
       'Unsuitable.Soil.and.Vegetation.Area.in.percent',
       'Unsuitable.Other.Land.Area.in.acres',
       'Unsuitable.Other.Land.Area.in.percent', 'SHAPEAREA', 'SHAPELEN',
       'Geographic.Area.Name',
       'Income.in.the.past.12.months.below.poverty.level',
       'Median.household.income.in.the.past.12.months', 'Total.Population',
       'Total.Population.of.one.race', 'Total.White.Population',
       'Total.African.American.Population', 'Total.American.Indian.Population',
       'Total.Asian.Population', 'Total.Native.Hawaiian.Population',
       'Total.Population.of.Other.Races', 'PovertyPerCapita', 'UTC_quart',
       'income_quart', 'UTCacres_quart',
       'Total.Possible.Planting.Area.in.percent2',
       'Possible.Vegetation.Planting.Area.in.percent2', 'priority_CBGs'],
      dtype='object')

In [249]:
df['Geographic.Area.Name'].head()

285    Block Group 5, Census Tract 76.01, District of...
216    Block Group 2, Census Tract 88.04, District of...
300    Block Group 1, Census Tract 76.05, District of...
171    Block Group 1, Census Tract 33.01, District of...
423    Block Group 1, Census Tract 99.03, District of...
Name: Geographic.Area.Name, dtype: object

In [250]:
df = df.drop(columns=['Unnamed: 0', 'X'])

In [251]:
df.head()

,census_bg,Total.Area.in.acres,Total.Land.Area.in.acres,Tree.Canopy.in.acres,Tree.Canopy.area.in.percent,Vegetation.in.acres,Vegetation.Percentage,Building.area.in.acres,Building.area.in.percent,Total.Impervious.Area.in.acres,...,Total.Asian.Population,Total.Native.Hawaiian.Population,Total.Population.of.Other.Races,PovertyPerCapita,UTC_quart,income_quart,UTCacres_quart,Total.Possible.Planting.Area.in.percent2,Possible.Vegetation.Planting.Area.in.percent2,priority_CBGs
285,110010076015,171.41,132.72,20.87,15.724834,50.03,37.695901,10.60,7.986739,60.59,...,4.0,0.0,15.0,0.029851,0.4,0.4,Q3,0.454792,0.359479,0.576525
216,110010088042,170.37,170.37,28.55,16.757645,58.66,34.430944,21.67,12.719375,82.94,...,23.0,1.0,76.0,0.035236,0.4,0.4,Q3,0.418618,0.344075,0.558105
300,110010076051,32.16,32.16,6.26,19.465174,9.05,28.140547,6.19,19.247512,16.86,...,4.0,0.0,10.0,0.033467,0.4,0.4,Q1,0.439677,0.281405,0.543244
171,110010033011,61.71,61.71,9.37,15.183925,23.67,38.356830,10.04,16.269648,28.67,...,50.0,0.0,35.0,0.000000,0.4,0.2,Q2,0.536218,0.383568,0.542781
423,110010099031,40.46,40.46,5.08,12.555610,10.48,25.902126,6.53,16.139397,24.81,...,3.0,1.0,14.0,0.028684,0.4,0.3,Q1,0.492832,0.259021,0.518519

In [252]:
df.to_csv('Priority_CBGs_File.csv')

In [179]:
import geopandas as gpd

In [180]:
gdf = gpd.read_file('Urban_Tree_Canopy_by_Census_Block_Group_in_2015 (1).geojson')

In [181]:
gdf.head()

,OBJECTID_1,OBJECTID,TRACT,BLKGRP,GEOID,GID,TOTAL_AC,LAND_AC,T_CAN_AC,T_CAN_PCT,...,PCT_CHG_11,GIS_ID,GLOBALID,CREATOR,CREATED,EDITOR,EDITED,SHAPEAREA,SHAPELEN,geometry
0,1,66,001600,4,110010016004,66,413.09,409.92,300.36,73.272834,...,-3.426928,temp_66,{FA0A3D90-3FAF-4745-AC2A-4EB65815451A},None,None,None,None,0,0,"POLYGON ((-77.03634 38.98640, -77.03634 38.987..."
1,2,63,001600,1,110010016001,63,118.47,118.47,47.14,39.790664,...,-5.891787,temp_63,{C8084982-F006-490A-AD3B-5538B96ED689},None,None,None,None,0,0,"POLYGON ((-77.02742 38.98330, -77.02708 38.983..."
2,3,58,001500,1,110010015001,58,772.10,770.79,653.75,84.815579,...,1.242308,temp_58,{23037077-9214-4A79-94CA-648AB87BF79E},None,None,None,None,0,0,"POLYGON ((-77.05004 38.98607, -77.05177 38.986..."
3,4,428,010300,2,110010103002,428,60.03,60.03,17.30,28.818924,...,0.978204,temp_428,{450DEC48-E273-483C-B534-B20399073644},None,None,None,None,0,0,"POLYGON ((-77.02317 38.98186, -77.02430 38.982..."
4,5,64,001600,2,110010016002,64,47.78,47.78,16.38,34.282126,...,-2.169014,temp_64,{58B87F53-A1B5-4162-9C33-793F38AA1EFD},None,None,None,None,0,0,"POLYGON ((-77.02643 38.97806, -77.02643 38.978..."

In [182]:
gdf.columns

Index(['OBJECTID_1', 'OBJECTID', 'TRACT', 'BLKGRP', 'GEOID', 'GID', 'TOTAL_AC',
       'LAND_AC', 'T_CAN_AC', 'T_CAN_PCT', 'VEG_AC', 'VEG_PCT', 'BLD_AC',
       'BLD_PCT', 'TO_IA_AC', 'TO_IA_PCT', 'ROAD_AC', 'ROAD_PCT', 'SWALK_AC',
       'SWALK_PCT', 'OT_IA_AC', 'OT_IA_PCT', 'WAT_AC', 'WAT_PCT', 'SOIL_AC',
       'SOIL_PCT', 'UTC_AC', 'UTC_PCT', 'PPA_V_AC', 'PPA_V_PCT', 'TO_PPA_AC',
       'TO_PPA_PCT', 'PPA_IA_AC', 'PPA_IA_PCT', 'UN_IA_AC', 'UN_IA_PCT',
       'TO_UN_AC', 'TO_UN_PCT', 'UN_SL_AC', 'UN_SL_PCT', 'UN_OT_AC',
       'UN_OT_PCT', 'WATER_AC', 'WATER_PCT', 'UTC_AC06', 'UTC_PCT06',
       'UTC_AC11', 'UTC_PCT11', 'PCT_CHG_06', 'PCT_CHG_11', 'GIS_ID',
       'GLOBALID', 'CREATOR', 'CREATED', 'EDITOR', 'EDITED', 'SHAPEAREA',
       'SHAPELEN', 'geometry'],
      dtype='object')

In [183]:
gdf = gdf.rename(columns = {'GEOID':'census_bg'})

In [184]:
gdf = gdf.drop(columns=['OBJECTID_1', 'OBJECTID', 'TRACT', 'BLKGRP', 'GID', 'TOTAL_AC',
       'LAND_AC', 'T_CAN_AC', 'T_CAN_PCT', 'VEG_AC', 'VEG_PCT', 'BLD_AC',
       'BLD_PCT', 'TO_IA_AC', 'TO_IA_PCT', 'ROAD_AC', 'ROAD_PCT', 'SWALK_AC',
       'SWALK_PCT', 'OT_IA_AC', 'OT_IA_PCT', 'WAT_AC', 'WAT_PCT', 'SOIL_AC',
       'SOIL_PCT', 'UTC_AC', 'UTC_PCT', 'PPA_V_AC', 'PPA_V_PCT', 'TO_PPA_AC',
       'TO_PPA_PCT', 'PPA_IA_AC', 'PPA_IA_PCT', 'UN_IA_AC', 'UN_IA_PCT',
       'TO_UN_AC', 'TO_UN_PCT', 'UN_SL_AC', 'UN_SL_PCT', 'UN_OT_AC',
       'UN_OT_PCT', 'WATER_AC', 'WATER_PCT', 'UTC_AC06', 'UTC_PCT06',
       'UTC_AC11', 'UTC_PCT11', 'PCT_CHG_06', 'PCT_CHG_11', 'GIS_ID',
       'GLOBALID', 'CREATOR', 'CREATED', 'EDITOR', 'EDITED', 'SHAPEAREA',
       'SHAPELEN', ])

In [185]:
gdf.head()

      census_bg                                           geometry
0  110010016004  POLYGON ((-77.03634 38.98640, -77.03634 38.987...
1  110010016001  POLYGON ((-77.02742 38.98330, -77.02708 38.983...
2  110010015001  POLYGON ((-77.05004 38.98607, -77.05177 38.986...
3  110010103002  POLYGON ((-77.02317 38.98186, -77.02430 38.982...
4  110010016002  POLYGON ((-77.02643 38.97806, -77.02643 38.978...

In [186]:
gdf['census_bg']= gdf['census_bg'].apply(pd.to_numeric)

In [187]:
final_df = df.merge(gdf, how='inner', on='census_bg')

In [188]:
final_df.head()

,census_bg,Total.Area.in.acres,Total.Land.Area.in.acres,Tree.Canopy.in.acres,Tree.Canopy.area.in.percent,Vegetation.in.acres,Vegetation.Percentage,Building.area.in.acres,Building.area.in.percent,Total.Impervious.Area.in.acres,...,Total.Native.Hawaiian.Population,Total.Population.of.Other.Races,PovertyPerCapita,UTC_quart,income_quart,UTCacres_quart,Total.Possible.Planting.Area.in.percent2,Possible.Vegetation.Planting.Area.in.percent2,priority_CBGs,geometry
0,110010001004,287.26,166.02,92.93,55.975184,5.89,3.547765,31.54,18.997711,67.01,...,NaN,NaN,NaN,0.1,0.1,Q4,0.123841,0.025479,0.124757,"POLYGON ((-77.05708 38.90770, -77.05738 38.907..."
1,110010002011,133.35,133.34,39.42,29.563522,19.01,14.256787,29.47,22.101395,74.91,...,0.0,0.0,NaN,0.2,0.3,Q4,0.271036,0.114369,0.316216,"POLYGON ((-77.07412 38.91259, -77.07433 38.912..."
2,110010002021,47.44,47.44,15.31,32.272344,3.78,7.967960,12.79,26.960371,28.35,...,0.0,13.0,0.0,0.2,0.1,Q3,0.214587,0.078204,0.211711,"POLYGON ((-77.06568 38.91183, -77.06583 38.912..."
3,110010002022,33.48,33.48,11.52,34.408602,2.86,8.542413,8.84,26.403823,19.01,...,0.0,12.0,0.0,0.2,0.1,Q2,0.227001,0.082139,0.217550,"POLYGON ((-77.06890 38.90774, -77.06850 38.907..."
4,110010002023,38.17,38.17,9.17,24.024103,1.68,4.401362,13.59,35.603877,27.32,...,0.0,14.0,0.0,0.3,0.1,Q2,0.214304,0.043752,0.235020,"POLYGON ((-77.06702 38.90509, -77.06678 38.905..."

In [195]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 450 entries, 0 to 449
Data columns (total 58 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   census_bg                                                           450 non-null    int64
 1   Total.Area.in.acres                                                 450 non-null    float64
 2   Total.Land.Area.in.acres                                            450 non-null    float64
 3   Tree.Canopy.in.acres                                                450 non-null    float64
 4   Tree.Canopy.area.in.percent                                         450 non-null    float64
 5   Vegetation.in.acres                                                 450 non-null    float64
 6   Vegetation.Percentage                                               450 non-null    float64
 7   Building.area.in.acres                                              450 non-null    float64
 8   Building.area.in.percent                                            450 non-null    float64
 9   Total.Impervious.Area.in.acres                                      450 non-null    float64
 10  Total.Impervious.Area.in.percent                                    450 non-null    float64
 11  Road.Acres                                                          450 non-null    float64
 12  Road.Area.in.percent                                                450 non-null    float64
 13  Sidewalk.Area.in.acres                                              450 non-null    float64
 14  Sidewalk.Area.in.percent                                            450 non-null    float64
 15  Other.Impervious.Area.in.acres                                      450 non-null    float64
 16  Other.Impervious.Area.in.percent                                    450 non-null    float64
 17  Surface.Water.Area.in.acres                                         450 non-null    float64
 18  Surface.Water.Area.in.percent                                       450 non-null    float64
 19  Soil.area.in.acres                                                  450 non-null    float64
 20  Soil.area.in.percent                                                450 non-null    float64
 21  Urban.Tree.Canopy.area.in.acres                                     450 non-null    float64
 22  Urban.Tree.Canopy.area.percent                                      450 non-null    float64
 23  Possible.Vegetation.Planting.Area.in.acres                          450 non-null    float64
 24  Possible.Vegetation.Planting.Area.in.percent                        450 non-null    float64
 25  Total.Possible.Planting.Area.in.acres                               450 non-null    float64
 26  Total.Possible.Planting.Area.in.percent                             450 non-null    float64
 27  Impervious.Possible.Planting.Area.in.acres                          450 non-null    float64
 28  Impervious.Possible.Planting.Area.in.percent                        450 non-null    float64
 29  Unsuitable.Impervious.Planting.Buildings.and.Roads.Area.in.acres    450 non-null    float64
 30  Unsuitable.Impervious.Planting.Buildings.and.Roads.Area.in.percent  450 non-null    float64
 31  Total.Unsuitable.Planting.Area.in.acres                             450 non-null    float64
 32  Total.Unsuitable.Planting.Area.in.percent                           450 non-null    float64
 33  Unsuitable.Soil.and.Vegetation.Area.in.acres                        450 non-null    float64
 34  Unsuitable.Soil.and.Vegetation.Area.in.percent                      450 non-null    float64
 35  Unsuitable.Other.Land.Area.in.acres                                 450 non-null    float64
 36  Unsuitable.Other.Land.Area.in.percent                               450 non-null    float64
 37  SHAPEAREA                                                           450 non-null    float64
 38  SHAPELEN                                                            450 non-null    float64
 39  Geographic.Area.Name                                                450 non-null    object
 40  Income.in.the.past.12.months.below.poverty.level                    450 non-null    int64
 41  Median.household.income.in.the.past.12.months                       450 non-null    int64
 42  Total.Population                                                    366 non-null    float64
 43  Total.Population.of.one.race                                        366 non-null    float64
 44  Total.White.Population                                              366 non-null    float64
 45  Total.African.American.Population                                   366 non-null    float64
 46  Total.American.Indian.Population                                    366 non-null    float64
 47  Total.Asian.Population                                              366 non-null    float64
 48  Total.Native.Hawaiian.Population                                    366 non-null    float64
 49  Total.Population.of.Other.Races                                     366 non-null    float64
 50  PovertyPerCapita                                                    365 non-null    float64
 51  UTC_quart                                                           450 non-null    float64
 52  income_quart                                                        450 non-null    float64
 53  UTCacres_quart                                                      450 non-null    object
 54  Total.Possible.Planting.Area.in.percent2                            450 non-null    float64
 55  Possible.Vegetation.Planting.Area.in.percent2                       450 non-null    float64
 56  priority_CBGs                                                       450 non-null    float64
 57  geometry                                                            450 non-null    geometry
dtypes: float64(52), geometry(1), int64(3), object(2)
memory usage: 207.4+ KB

In [254]:
# write the output to a csv file for further use
final_df.to_csv('UTC_Census_Data_Merged_GEO.csv')

In [190]:
gdf = gpd.GeoDataFrame(final_df, geometry = final_df.geometry)

In [193]:
gdf.to_file(driver = 'ESRI Shapefile', filename= "Priority_CBGs_File.shp")

/Users/lensingh/.conda/envs/untitled/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  """Entry point for launching an IPython kernel.

In [194]:
gdf.columns

Index(['census_bg', 'Total.Area.in.acres', 'Total.Land.Area.in.acres',
       'Tree.Canopy.in.acres', 'Tree.Canopy.area.in.percent',
       'Vegetation.in.acres', 'Vegetation.Percentage',
       'Building.area.in.acres', 'Building.area.in.percent',
       'Total.Impervious.Area.in.acres', 'Total.Impervious.Area.in.percent',
       'Road.Acres', 'Road.Area.in.percent', 'Sidewalk.Area.in.acres',
       'Sidewalk.Area.in.percent', 'Other.Impervious.Area.in.acres',
       'Other.Impervious.Area.in.percent', 'Surface.Water.Area.in.acres',
       'Surface.Water.Area.in.percent', 'Soil.area.in.acres',
       'Soil.area.in.percent', 'Urban.Tree.Canopy.area.in.acres',
       'Urban.Tree.Canopy.area.percent',
       'Possible.Vegetation.Planting.Area.in.acres',
       'Possible.Vegetation.Planting.Area.in.percent',
       'Total.Possible.Planting.Area.in.acres',
       'Total.Possible.Planting.Area.in.percent',
       'Impervious.Possible.Planting.Area.in.acres',
       'Impervious.Possible.Planting.Area.in.percent',
       'Unsuitable.Impervious.Planting.Buildings.and.Roads.Area.in.acres',
       'Unsuitable.Impervious.Planting.Buildings.and.Roads.Area.in.percent',
       'Total.Unsuitable.Planting.Area.in.acres',
       'Total.Unsuitable.Planting.Area.in.percent',
       'Unsuitable.Soil.and.Vegetation.Area.in.acres',
       'Unsuitable.Soil.and.Vegetation.Area.in.percent',
       'Unsuitable.Other.Land.Area.in.acres',
       'Unsuitable.Other.Land.Area.in.percent', 'SHAPEAREA', 'SHAPELEN',
       'Geographic.Area.Name',
       'Income.in.the.past.12.months.below.poverty.level',
       'Median.household.income.in.the.past.12.months', 'Total.Population',
       'Total.Population.of.one.race', 'Total.White.Population',
       'Total.African.American.Population', 'Total.American.Indian.Population',
       'Total.Asian.Population', 'Total.Native.Hawaiian.Population',
       'Total.Population.of.Other.Races', 'PovertyPerCapita', 'UTC_quart',
       'income_quart', 'UTCacres_quart',
       'Total.Possible.Planting.Area.in.percent2',
       'Possible.Vegetation.Planting.Area.in.percent2', 'priority_CBGs',
       'geometry'],
      dtype='object')

In [201]:
final_df = final_df.sort_values(by='priority_CBGs', ascending=False).head(10)

In [216]:
final_df.head(10)

,census_bg,Total.Area.in.acres,Total.Land.Area.in.acres,Tree.Canopy.in.acres,Tree.Canopy.area.in.percent,Vegetation.in.acres,Vegetation.Percentage,Building.area.in.acres,Building.area.in.percent,Total.Impervious.Area.in.acres,...,Total.Native.Hawaiian.Population,Total.Population.of.Other.Races,PovertyPerCapita,UTC_quart,income_quart,UTCacres_quart,Total.Possible.Planting.Area.in.percent2,Possible.Vegetation.Planting.Area.in.percent2,priority_CBGs,geometry
285,110010076015,171.41,132.72,20.87,15.724834,50.03,37.695901,10.60,7.986739,60.59,...,0.0,15.0,0.029851,0.4,0.4,Q3,0.454792,0.359479,0.576525,"POLYGON ((-76.98435 38.86666, -76.98434 38.866..."
216,110010088042,170.37,170.37,28.55,16.757645,58.66,34.430944,21.67,12.719375,82.94,...,1.0,76.0,0.035236,0.4,0.4,Q3,0.418618,0.344075,0.558105,"POLYGON ((-76.98082 38.90406, -76.98064 38.904..."
300,110010076051,32.16,32.16,6.26,19.465174,9.05,28.140547,6.19,19.247512,16.86,...,0.0,10.0,0.033467,0.4,0.4,Q1,0.439677,0.281405,0.543244,"POLYGON ((-76.97541 38.86453, -76.97517 38.865..."
171,110010033011,61.71,61.71,9.37,15.183925,23.67,38.356830,10.04,16.269648,28.67,...,0.0,35.0,0.000000,0.4,0.2,Q2,0.536218,0.383568,0.542781,"POLYGON ((-77.00904 38.91813, -77.00904 38.919..."
423,110010099031,40.46,40.46,5.08,12.555610,10.48,25.902126,6.53,16.139397,24.81,...,1.0,14.0,0.028684,0.4,0.3,Q1,0.492832,0.259021,0.518519,"POLYGON ((-76.91380 38.88977, -76.91404 38.889..."
224,110010074042,62.89,62.85,14.67,23.341289,22.95,36.515513,6.44,10.246619,24.83,...,1.0,39.0,0.008079,0.3,0.3,Q3,0.482100,0.365155,0.516877,"POLYGON ((-76.98100 38.84997, -76.98101 38.850..."
219,110010089041,69.73,69.73,10.59,15.187150,18.40,26.387495,15.32,21.970457,39.70,...,0.0,56.0,0.147594,0.4,0.4,Q2,0.398107,0.241646,0.514198,"POLYGON ((-76.97139 38.90346, -76.97147 38.903..."
275,110010074092,38.97,38.97,8.37,21.478060,11.34,29.099307,6.28,16.114960,19.25,...,0.0,13.0,0.104099,0.3,0.4,Q2,0.443931,0.290223,0.512198,"POLYGON ((-76.97204 38.84405, -76.97193 38.844..."
292,110010095083,56.67,56.67,14.50,25.586730,17.18,30.315864,6.54,11.540498,25.00,...,0.0,16.0,0.028777,0.3,0.4,Q3,0.423152,0.303159,0.509397,"POLYGON ((-76.98818 38.95454, -76.98846 38.954..."
218,110010089032,19.99,19.99,2.91,14.557279,6.05,30.265133,4.04,20.210105,11.03,...,0.0,43.0,0.044866,0.4,0.3,Q1,0.430715,0.280640,0.504056,"POLYGON ((-76.97621 38.90629, -76.97621 38.906..."